apiVersion: v1
kind: Namespace
metadata:
  name: elastic-stack
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace:  elastic-stack
spec:
  clusterIP: None
  selector:
    app: elasticsearch
  ports:
    - name: transport
      port: 9300
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ku
  namespace: elastic-stack
spec:
  type: NodePort
  ports:
    - port: 9200 # 这个servie的端口
      targetPort: 9200 # 映射到容器的端口
      nodePort: 30124 # 对外暴露的端口
  selector:
    app: elasticsearch
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es-cluster
  namespace: elastic-stack
spec:
  serviceName: elasticsearch
  replicas: 2
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
          securityContext:
            privileged: true
            capabilities:
              add:
                - IPC_LOCK
                - SYS_RESOURCE
          ports:
            - containerPort: 9200
              name: rest
              protocol: TCP
            - containerPort: 9300
              name: inter-node
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
          env:
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: discovery.seed_hosts
              value: "elasticsearch"
            - name: cluster.initial_master_nodes
              value: "es-cluster-0"
            - name: cluster.name
              value: "lanhai-es"
            - name: bootstrap.memory_lock
              value: "false"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
      initContainers:
        - name: increase-vm-max-map
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: elasticsearch
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-cluster-data-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/es-cluster-data-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - cp1.k8s.lanhai.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-cluster-data-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/es-cluster-data-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - cp1.k8s.lanhai.com
