apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-user
  namespace: jenkins
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkinshome
  namespace: jenkins
  annotations:
    volume.beta.kubernetes.io/storage-class: "example-nfs"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: jenkins-user
  namespace: jenkins
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  selector:
    matchLabels:
      run: jenkins
  replicas: 1
  template:
    metadata:
      labels:
        run: jenkins
    spec:
      serviceAccountName: jenkins-user
      containers:
      - image: jenkins/jenkins:lts-jdk11
        imagePullPolicy: Always
        name: jenkins
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: jenkinshome
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkinshome
        persistentVolumeClaim:
          claimName: jenkinshome
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: jenkins
  name: jenkins
  namespace: jenkins
spec:
  ports:
  - name: web
    nodePort: 30217
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: agent
    nodePort: 30317
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    run: jenkins
  type: NodePort